alibaba:
  base_url: https://www.alibaba.com
  crawler_class: AlibabaCrawler
  display_name: 阿里巴巴
  headers:
    accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    accept-language: en-US,en;q=0.5
    authority: www.alibaba.com
  name: alibaba
amazon:
  base_url: https://www.amazon.com
  crawler_class: AmazonCrawler
  display_name: 亚马逊
  headers:
    accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    accept-language: en-US,en;q=0.5
    authority: www.amazon.com
  name: amazon
ebay:
  base_url: https://www.ebay.com
  crawler_class: EbayCrawler
  display_name: eBay
  headers:
    accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    accept-language: en-US,en;q=0.5
    authority: www.ebay.com
  name: ebay
# 京东配置 - 修复版
jd:
  name: jd
  display_name: 京东
  base_url: https://www.jd.com
  crawler_class: JDCrawler
  headers:
    authority: search.jd.com
    accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
    accept-language: zh-CN,zh;q=0.9
    cache-control: no-cache
    pragma: no-cache
    referer: https://www.jd.com/
    sec-ch-ua: '"Chromium";v="120", "Not A(Brand";v="99", "Google Chrome";v="120"'
    sec-ch-ua-mobile: ?0
    sec-ch-ua-platform: '"Windows"'
    sec-fetch-dest: document
    sec-fetch-mode: navigate
    sec-fetch-site: same-site
    upgrade-insecure-requests: '1'
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
